function normalizeBangladeshPhone(phone) {
  if (!phone) return null;

  let normalized = String(phone).trim();

  // Remove spaces, dashes, parentheses, etc.
  normalized = normalized.replace(/\D/g, "");

  // 018XXXXXXXX → 88018XXXXXXXX
  if (normalized.startsWith("01")) {
    normalized = `88${normalized}`;
  }

  // 88018XXXXXXXX → already correct
  if (normalized.startsWith("880")) {
    return normalized;
  }

  return null;
}

export function openEmergencyWhatsApp(phone) {
  const normalizedPhone = normalizeBangladeshPhone(phone);

  if (!normalizedPhone) {
    return;
  }

  // This message is fixed by MediSync.
  // It is NOT generated by Gemini.
  const message =
    "আমি অনেক অসুস্থ বোধ করছি এবং আমার এখন সাহায্য দরকার। দয়া করে আমার সাথে দ্রুত যোগাযোগ করুন।";

  const whatsappUrl =
    `https://wa.me/${normalizedPhone}` +
    `?text=${encodeURIComponent(message)}`;

  window.open(whatsappUrl, "_blank", "noopener,noreferrer");
}