// server/validators/profile.schema.js

// Validates profile create/update requests.
// Mirrors the payload generated by client settingsForm.js.

import { z } from "zod";

import {
  emailSchema,
  isFutureDate,
  isValidDate,
  optionalText,
  phoneSchema,
  requiredText,
} from "./common.js";

const BLOOD_GROUPS = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"];

const GENDERS = ["", "Male", "Female", "Other"];

const BLOOD_DONOR_STATUSES = ["", "yes", "no", "willingly"];

const BLOOD_DONATION_COMPENSATIONS = ["", "500", "none"];

const RELATIONS = [
  "Son",
  "Daughter",
  "Husband",
  "Wife",
  "Father",
  "Mother",
  "Brother",
  "Sister",
  "Best Friend",
  "Friend",
  "Doctor",
  "Personal Health Assistant",
  "Other",
];

const dobSchema = z
  .string()
  .trim()
  .refine((value) => /^\d{4}-\d{2}-\d{2}$/.test(value), {
    message: "Date of birth must be a valid date.",
  })
  .refine(isValidDate, {
    message: "Please provide a valid date of birth.",
  })
  .refine((value) => !isFutureDate(value), {
    message: "Date of birth cannot be in the future.",
  })
  .refine(
    (value) => {
      const dob = new Date(`${value}T00:00:00`);
      const now = new Date();

      let age = now.getFullYear() - dob.getFullYear();

      const birthdayPassed =
        now.getMonth() > dob.getMonth() ||
        (now.getMonth() === dob.getMonth() && now.getDate() >= dob.getDate());

      if (!birthdayPassed) {
        age -= 1;
      }

      return age <= 120;
    },
    {
      message: "Date of birth is outside the supported age range.",
    },
  );

const donationDateSchema = z
  .string()
  .trim()
  .refine(isValidDate, {
    message: "Last blood donation must be a valid date.",
  })
  .refine((value) => !isFutureDate(value), {
    message: "Last blood donation cannot be in the future.",
  });

const heightSchema = z
  .object({
    feet: z.number().int().nullable(),
    inches: z.number().int().nullable(),
  })
  .superRefine((height, context) => {
    const hasFeet = height.feet !== null;
    const hasInches = height.inches !== null;

    if (!hasFeet && !hasInches) {
      return;
    }

    if (!hasFeet || !hasInches) {
      context.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["feet"],
        message: "Please provide both feet and inches.",
      });

      return;
    }

    if (height.feet < 1 || height.feet > 9) {
      context.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["feet"],
        message: "Height in feet must be between 1 and 9.",
      });
    }

    if (height.inches < 0 || height.inches > 11) {
      context.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["inches"],
        message: "Height in inches must be between 0 and 11.",
      });
    }
  });

const emergencyContactSchema = z
  .object({
    relation: z.enum(RELATIONS, {
      message: "Please select a valid emergency contact relation.",
    }),

    name: requiredText(
      50,
      "Please enter the emergency contact name.",
      "Emergency contact name cannot exceed 50 characters.",
    ),

    phone: phoneSchema,

    email: emailSchema,
  })
  .superRefine((contact, context) => {
    if (!contact.phone && !contact.email) {
      context.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["phone"],
        message:
          "Each emergency contact must have a phone number or email address.",
      });
    }
  });

const locationSchema = z
  .object({
    district: optionalText(100),
    upazila: optionalText(100),
    streetAddress: optionalText(300),
  })
  .strict();

export const profileSchema = z
  .object({
    // Name is part of the request because the controller updates User.name.
    name: requiredText(
      50,
      "Name is required.",
      "Name cannot exceed 50 characters.",
    ),

    dob: dobSchema.nullable(),

    gender: z.enum(GENDERS, {
      message: "Please select a valid gender.",
    }),

    height: heightSchema,

    bloodGroup: z.enum(["", ...BLOOD_GROUPS], {
      message: "Please select a valid blood group.",
    }),

    allergies: optionalText(1000, "Allergies cannot exceed 1000 characters."),

    chronicIllnesses: z
      .array(
        z
          .string()
          .trim()
          .min(1, {
            message: "Chronic illness cannot be empty.",
          })
          .max(100, {
            message: "Chronic illness cannot exceed 100 characters.",
          }),
      )
      .max(10, {
        message: "You can select a maximum of 10 chronic illnesses.",
      }),

    surgeries: optionalText(
      2000,
      "Surgery information cannot exceed 2000 characters.",
    ),

    emergencyContacts: z.array(emergencyContactSchema).max(3, {
      message: "You can add a maximum of 3 emergency contacts.",
    }),

    bloodDonorStatus: z.enum(BLOOD_DONOR_STATUSES, {
      message: "Please select a valid blood donor status.",
    }),

    bloodDonationCompensation: z.enum(BLOOD_DONATION_COMPENSATIONS, {
      message: "Please select a valid blood donation compensation option.",
    }),

    lastBloodDonation: donationDateSchema.nullable(),

    bloodDonationContactNumber: phoneSchema,

    location: locationSchema,
  })
  .strict()
  .superRefine((profile, context) => {
    const isDonor =
      profile.bloodDonorStatus === "yes" ||
      profile.bloodDonorStatus === "willingly";

    if (isDonor) {
      if (!profile.bloodDonationContactNumber) {
        context.addIssue({
          code: z.ZodIssueCode.custom,
          path: ["bloodDonationContactNumber"],
          message:
            "A contact number is required when you are available to donate blood.",
        });
      }

      if (!profile.location.district) {
        context.addIssue({
          code: z.ZodIssueCode.custom,
          path: ["location", "district"],
          message: "Please select your district.",
        });
      }

      if (!profile.location.upazila) {
        context.addIssue({
          code: z.ZodIssueCode.custom,
          path: ["location", "upazila"],
          message: "Please select your upazila.",
        });
      }
    }

    if (profile.bloodDonationCompensation !== "" && !isDonor) {
      context.addIssue({
        code: z.ZodIssueCode.custom,
        path: ["bloodDonationCompensation"],
        message:
          "Blood donation compensation can only be selected for available donors.",
      });
    }
  });
